---
env:
  browser: true
  es6: true
extends: airbnb-base
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
  import/no-extraneous-dependencies: ["error", {"devDependencies": true}]
