---
version: "2.4"
services:
  postgres:
    image: postgres:15
    network_mode: host
    environment:
      POSTGRES_DB: django-wtf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_dump:/tmp/db_dump

  redis:
    image: redis:6
    network_mode: host

  mailpit:
    image: axllent/mailpit:v1.12
    network_mode: host

volumes:
  pgdata:
