---
version: '2.4'
services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: django-apps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_dump:/tmp/db_dump

  redis:
    image: redis:6
    ports:
      - '6379:6379'

volumes:
  pgdata:
