[tool.poetry]
name = "project"
version = "0.0.1"
description = "djangoapps.dev"
authors = ["Dani Hodovic <dani-hodovic@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.5"
psycopg2 = "^2.8.5"
whitenoise = "^5.0.1"
django-anymail = {extras = ["mailgun"], version = "^7.0.0"}
django-storages = {extras = ["boto3"], version = "^1.9.1"}
gunicorn = "^20.0.4"
django-extensions = "^2.2.9"
django-environ = "^0.4.5"
djangorestframework = "^3.11.0"
django-crispy-forms = "^1.9.0"
django-model-utils = "^4.0.0"
django-meta = "^1.6.1"
django-health-check = "^3.12.1"
django-allauth = "^0.41.0"
django-filter= "^2.2.0"
django-debug-toolbar = "^2.2"
pudb = "^2019.2"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
pytest-django = "^3.9.0"
black = "^19.10b0"
coverage = "^5.0.4"
factory-boy = "^2.12.0"
isort = "^4.3.21"
mypy = "^0.770"
pylint-django = "^2.0.14"
pylint = "^2.4.4"
pytest-cov = "^2.8.1"
django-stubs = "^1.5.0"
djangorestframework-stubs = "^1.1.0"
werkzeug = "^1.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
