[tool.poetry]
name = "project"
version = "0.0.1"
description = "djangoapps.dev"
authors = ["Dani Hodovic <dani-hodovic@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
psycopg2 = "^2.9.3"
whitenoise = "^6.0.0"
django-anymail = "^8.5"
gunicorn = "^20.1.0"
django-extensions = "^3.1.5"
django-environ = "^0.8.1"
django-model-utils = "^4.2.0"
django-meta = {git = "https://github.com/ivanchenkodmitry/django-meta", rev = "patch-1"}
django-health-check = "^3.16.5"
django-allauth = "^0.48.0"
django-filter= "^21.1"
django-debug-toolbar = "^3.2.4"
pudb = "^2019.2"
celery = "^5.2.3"
Django = "^4.0.2"
django-celery-beat = {git = "https://github.com/celery/django-celery-beat", rev = "fa73034be892052893e4ef17926ef3a5d4a21ea2"}
django-allauth-ui = "^0.0.15"
django-widget-tweaks = "^1.4.12"
redis = "^4.1.3"
requests = "^2.27.1"
django-redis = "^5.2.0"
ptipython = "^1.0.1"
ptpython = "^3.0.20"
argon2-cffi = "^21.3.0"
django-constance = {extras = ["database"], version = "^2.8.0"}
django-toolshed = "^0.5.3"
django-tailwind = "^3.1.1"
django-browser-reload = "^1.3.0"
django-cacheops = "^6.0"
django-import-export = "^2.8.0"
django-admin-interface = "^0.19.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-django = "^4.5.2"
black = "^22.1.0"
coverage = "^6.3.1"
factory-boy = "^3.2.1"
isort = "^5.10.1"
mypy = "^0.931"
pylint-django = "^2.0.14"
pylint = "^2.4.4"
pytest-cov = "^3.0.0"
django-stubs = "^1.9.0"
pylint-celery = "^0.3"
Werkzeug = "^2.0.3"
docker-compose = "^1.29.2"
django-coverage-plugin = "^2.0.2"
responses = "^0.18.0"
types-requests = "^2.27.12"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
skip_numeric_underscore_normalization = true
exclude = ".*(venv|virtualenv|.poetry|migrations|node_modules)"
