# Generated by Django 4.0.2 on 2022-03-22 20:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='repository',
            name='type',
            field=models.CharField(blank=True, choices=[('project', 'project'), ('app', 'app')], max_length=30, null=True),
        ),
    ]
