# Generated by Django 4.0.2 on 2022-04-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repository_archived_repository_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repositorystars',
            unique_together={('repository', 'created_at')},
        ),
    ]
