# Generated by Django 4.0.2 on 2022-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_followers_alter_profilefollowers_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(blank=True, choices=[('Reddit', 'Reddit'), ('Hacker News', 'Hacker News')], max_length=30, null=True)),
                ('upvotes', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
