# Generated by Django 4.0.2 on 2022-05-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pypiproject_pypirelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypiproject',
            name='license',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pypiproject',
            name='requires_python',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pypirelease',
            name='version',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='pypirelease',
            unique_together={('project', 'version')},
        ),
    ]
