# Generated by Django 4.0.2 on 2022-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pypiproject_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.Category'),
        ),
    ]
