# Generated by Django 4.0.2 on 2022-05-11 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_socialnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PypiProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('author', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('homepage', models.URLField()),
                ('summary', models.CharField(max_length=300)),
                ('version', models.CharField(max_length=12)),
                ('requires_python', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=20)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.repository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PypiRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True)),
                ('uploaded_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pypiproject')),
            ],
        ),
    ]
