# Generated by Django 4.0.2 on 2022-06-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_repository_readme_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pypirelease',
            options={'get_latest_by': 'uploaded_at'},
        ),
        migrations.AlterField(
            model_name='pypirelease',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', related_query_name='release', to='core.pypiproject'),
        ),
    ]
